services:
  - type: web
    name: spotter-hos-trip-planner
    runtime: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: SECURE_SSL_REDIRECT
        value: "true"
      - key: TRUSTED_PROXY
        value: "*"
      - key: MAP_USER_AGENT
        sync: false
